#!/bin/csh

foreach i ($*)
	set i=`echo $i | sed s/\\.l1//g`
	set i=`echo $i | sed s/\\.out//g`
	set i=`echo $i | sed s/\\.vgout//g`
	set i=`echo $i | sed s/\\.failed//g`
	set i=`echo $i | sed s/\\.vgfailed//g`
	diff -u $1.l1.out $1.l1.failed
end
