#!/bin/csh
set args = ()
foreach i ($*)
	set i=`echo $i | sed s/\\.l1//g`
	set i=`echo $i | sed s/\\.out//g`
	set i=`echo $i | sed s/\\.vgout//g`
	set i=`echo $i | sed s/\\.failed//g`
	set i=`echo $i | sed s/\\.vgfailed//g`
	set args = ( $i.l1 $args ) 
end
./test.py $args

