#!/bin/csh

foreach i ($*)
	set i=`echo $i | sed s/\\.l1//g`
	set i=`echo $i | sed s/\\.out//g`
	set i=`echo $i | sed s/\\.failed//g`
	set i=`echo $i | sed s/\\.vgfailed//g`
	cp $i.l1.failed $i.l1.out
	rm $i.l1.failed
	echo $i
end
