#!/bin/bash

P=$0
D=`dirname ${P}`

PROG=""

while [ -n "$1" ] ; do
	case "$1" in
	"-o")
		if [ -z "$2" ] ; then echo -e "Usage:\ndcc -o <target> -- <l1 option> ..." 1>&2 ; exit 1 ; fi
		PROG="$2"
		shift
	;;
	"--")
		shift
		break
	;;
	*)
		echo -e "Unknown option: $1\nUsage:\ndcc -o <target> -- <l1 option> ..." 1>&2
		exit 1
	;;
	esac
	shift
done

if [ -z "${PROG}" ] ; then
	echo -e "Usage:\ndcc -o <target> -- <l1 option> ..." 1>&2 ; exit 1
fi

rm -f ${PROG}

TD=`mktemp -t dcc_relink_XXXXX -d`
if [ -z "${TD}" ] ; then
	echo -e "unable to create tempdir" 1>&2
	exit 1
fi

T="${TD}/heapobj.o"
H="${TD}/app.heap"

if [ -f "${T}" ] ; then
	rm "${T}" || exit 1
fi

if [ -f "${H}" ] ; then
	rm "${H}" || exit 1
fi

if [ -z "${PROG}" ] ; then
	echo -e "no prog"
	exit 1
fi

"${D}"/../l1 -d "${H}" "$@" || exit 1

make -C "${D}"/.. relink RLTARG="${PROG}" HEAP="${H}" HEAPO="${T}" RLX="${T}" IDIR="${TD}/"

rm -rf "${TD}"
